[functions.scan-cccd]
verify_jwt = false

[functions.google-drive-upload]
verify_jwt = false

[functions.weekly-backup]
verify_jwt = false

[functions.export-trainee-pdf]
verify_jwt = false

project_id = "bcltzwpnhfpbfiuhfkxi"
