-- Step 1: Drop the trigger that depends on contract_term
DROP TRIGGER IF EXISTS trigger_calculate_return_date ON public.trainees;

-- Step 2: Drop views that depend on contract_term column
DROP VIEW IF EXISTS public.trainees_with_workflow;
DROP VIEW IF EXISTS public.trainees_basic;

-- Step 3: Change contract_term column from INTEGER to NUMERIC to support decimal values like 0.5 (6 months)
ALTER TABLE public.trainees 
ALTER COLUMN contract_term TYPE numeric USING contract_term::numeric;

-- Step 4: Also update the orders table
ALTER TABLE public.orders 
ALTER COLUMN contract_term TYPE numeric USING contract_term::numeric;

-- Step 5: Recreate trainees_basic view
CREATE VIEW public.trainees_basic AS
SELECT id,
    trainee_code,
    full_name,
    furigana,
    trainee_type,
    progression_stage,
    simple_status,
    birth_date,
    gender,
    phone,
    zalo,
    facebook,
    departure_date,
    return_date,
    expected_entry_month,
    notes,
    created_at,
    updated_at,
    birthplace,
    cccd_number,
    cccd_date,
    cccd_place,
    email,
    passport_number,
    passport_date,
    ethnicity,
    marital_status,
    current_situation,
    source,
    education_level,
    temp_address,
    current_address,
    permanent_address,
    household_address,
    parent_phone_1,
    parent_phone_2,
    height,
    weight,
    blood_group,
    vision_left,
    vision_right,
    dominant_hand,
    smoking,
    tattoo,
    drinking,
    health_status,
    hobbies,
    entry_date,
    class_id,
    enrollment_status,
    interview_pass_date,
    receiving_company_id,
    union_id,
    job_category_id,
    interview_count,
    registration_date,
    document_submission_date,
    otit_entry_date,
    nyukan_entry_date,
    coe_date,
    visa_date,
    absconded_date,
    early_return_date,
    early_return_reason,
    contract_end_date,
    contract_term,
    expected_return_date,
    photo_url,
    policy_category,
    religion,
    tattoo_description
FROM trainees;

-- Step 6: Recreate trainees_with_workflow view
CREATE VIEW public.trainees_with_workflow AS
SELECT t.id,
    t.trainee_code,
    t.full_name,
    t.furigana,
    t.trainee_type,
    t.progression_stage,
    t.simple_status,
    t.birth_date,
    t.gender,
    t.phone,
    t.zalo,
    t.facebook,
    t.departure_date,
    t.return_date,
    t.expected_entry_month,
    t.notes,
    t.created_at,
    t.updated_at,
    t.birthplace,
    t.cccd_number,
    t.cccd_date,
    t.cccd_place,
    t.email,
    t.passport_number,
    t.passport_date,
    t.ethnicity,
    t.marital_status,
    t.current_situation,
    t.source,
    t.education_level,
    t.temp_address,
    t.current_address,
    t.permanent_address,
    t.household_address,
    t.parent_phone_1,
    t.parent_phone_2,
    t.height,
    t.weight,
    t.blood_group,
    t.vision_left,
    t.vision_right,
    t.dominant_hand,
    t.smoking,
    t.tattoo,
    t.drinking,
    t.health_status,
    t.hobbies,
    t.entry_date,
    t.class_id,
    t.enrollment_status,
    t.interview_pass_date,
    t.receiving_company_id,
    t.union_id,
    t.job_category_id,
    t.interview_count,
    t.registration_date,
    t.document_submission_date,
    t.otit_entry_date,
    t.nyukan_entry_date,
    t.coe_date,
    t.visa_date,
    t.absconded_date,
    t.early_return_date,
    t.early_return_reason,
    t.contract_end_date,
    t.contract_term,
    t.expected_return_date,
    t.photo_url,
    t.policy_category,
    t.religion,
    t.tattoo_description,
    tw.current_stage,
    tw.sub_status,
    tw.owner_department_id,
    tw.transitioned_at,
    tw.transitioned_by
FROM trainees t
LEFT JOIN trainee_workflow tw ON t.id = tw.trainee_id;

-- Step 7: Recreate the trigger
CREATE TRIGGER trigger_calculate_return_date
BEFORE INSERT OR UPDATE OF departure_date, contract_term 
ON public.trainees 
FOR EACH ROW 
EXECUTE FUNCTION calculate_expected_return_date();