// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://bcltzwpnhfpbfiuhfkxi.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_nQkqreudsHeEhvFbczMJuw_NdUaoXcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Đảm bảo Supabase tự đọc token/session từ link reset mật khẩu
    // (access_token/refresh_token hoặc code) và phát event PASSWORD_RECOVERY.
    detectSessionInUrl: true,
  }
});